### ISSUE TITLE
Feature Request: Support for plugins listed in netlify.toml files

### ISSUE THREAD

**Issue by princefishthrower** [depcheck/depcheck#627]
### Feature request description

Awesome tool! Just discovering this tool today, man I had some dependencies from years ago... sheesh

Anyway, I would really like it if plugins in netlify.toml files were picked up. Currently they aren't, and listed incorrectly as unused.

### Code snippets

How the dependency is used (if applicable):

In a `netlify.toml` file, like so

```toml
[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'suffix'
```

How the dependency is listed in package.json (if applicable):

```
"devDependencies": {
    ...
    "netlify-plugin-contextual-env": "^0.3.0",
}
```

### Any extra info

I could potentially create a pull request for this feature - I haven't looked at how this library works, if it's regex-based or similar I can't imagine this would be too hard.
