### ISSUE TITLE
[false negative] SCSS variables are partially broken

### ISSUE THREAD

**Issue by theKashey** [depcheck/depcheck#632]
### Bug Description

This is not the issue of depcheck, but scss-parser - https://github.com/salesforce-ux/scss-parser/issues/38 - adding here for traceability

Behavior - scss-parser generates a run time exception parsing file content, as a result used packages are not tracked

### Code snippets

```scss
@use "~@ui/styles/mixin";
@use "~@ui/styles/media";

.button {
  @include mixin.until(media.$sm) { // fails here
    width: 100%;
  }
}
```
