### ISSUE TITLE
False alert for css modules after upgrade from v0.9.2

### ISSUE THREAD

**Issue by meskill** [depcheck/depcheck#712]
### Bug Description

We have a monorepo that uses depcheck for dependencies control.

After upgrading from depcheck v0.9.2 to v1+ we got one failed unit-test related to css modules. 

Source code for [test](https://github.com/Tinkoff/tramvai/blob/main/tools/monorepo/depscheck/src/depscheck.spec.ts#L123) and [fixture](https://github.com/Tinkoff/tramvai/blob/main/tools/monorepo/depscheck/src/__fixtures__/cssModules/index.css) 

### Code snippets

Where the dependency is used:

```css
@import "~pkg-m/m.css";
@import "~@pkg-m/m/m.css";
@value spacingXL from "pkg-m/m.css";
@value spacingXL from "@pkg-m/m/m.css";

.content {
  composes: a from "~pkg-m/m.css";
  composes: a from "~@pkg-m/m/m.css";
}
```

Where the dependency is listed in package.json:

```json
{
  "name": "with-css-modules",
  "version": "1.0.0",
  "dependencies": {
    "pkg-m": "^1.2.3",
    "@pkg-m/m": "^1.2.3"
  },
  "license": "Apache-2.0"
}
```

### Versions

- `node -v`: v16.14.0
- `npm -v`: 8.3.1
- `depcheck --version`: 1.4.3

### Extra info

Output of `depcheck --json`:
```json
{"dependencies":["pkg-m","@pkg-m/m"],"devDependencies":[],"missing":{},"using":{},"invalidFiles":{},"invalidDirs":{}}
```
